services:
  mysql:
    image: mysql:8.0
    container_name: mfa_mysql_app
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
  redis:
    image: redis:7
    container_name: mfa_redis_app
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env

  server:
    image: nqkhanh0908/mfa-server:v1.0.0
    build: .
    container_name: mfa_server_app
    restart: always
    ports:
      - "${APPLICATION_PORT}:8080"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      # Server config
      APPLICATION_NAME: ${APPLICATION_NAME}
      APPLICATION_HOST: ${APPLICATION_HOST}
      APPLICATION_PORT: ${APPLICATION_PORT}
      SERVER_SERVLET_CONTEXT_PATH: ${SERVER_SERVLET_CONTEXT_PATH}

      # Database config
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Swagger config
      SPRINGDOC_SWAGGER_UI_PATH: ${SPRINGDOC_SWAGGER_UI_PATH}

      # Mail Config
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}

      # Redis config
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}

      # JWT config
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      # Oath2 config
      ## Google
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      ## GitHub
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}
      GITHUB_SCOPE: ${GITHUB_SCOPE}
      GITHUB_AUTHORIZATION_URI: ${GITHUB_AUTHORIZATION_URI}
      GITHUB_TOKEN_URI: ${GITHUB_TOKEN_URI}
      GITHUB_USER_INFO_URI: ${GITHUB_USER_INFO_URI}

volumes:
  mysql_data:
    name: mfa_mysql_data